language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
  
node_js:
  - "6"

install:
   - composer install
   - npm install
   - gulp
   
before_script:
   - npm install -g gulp
script: gulp
