language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

node_js:
  - "6"

before_install:
  - npm install npm -g

before_script:
  - composer install
  - npm install
  - npm install -g gulp

script:
  - gulp
  - vendor/bin/phpunit
